Neuer Endpunkt für das Entscheidungsreifesignal hinzugefügt
europace/baufismart-vorgaenge-api pull request #79
Opened 2020-10-08 14:41 UTC by mdehmel

Der neue Endpunkt für das Entcheidungsreifesignal wurde in die Swagger aufgenommen

2020-10-08 14:52 UTC, schmidthappens requested changes

2020-10-08 14:52 UTC, schmidthappens commented on swagger.json
> +    "EntscheidungsreifeDTO": {
Was mit auffält ist, dass das Feld hier DTO heißt. Wir geben Typen eigentlich ohne technischen Suffix raus.

2020-10-08 14:52 UTC, schmidthappens commented on swagger.yaml
> +  EntscheidungsreifeDTO:
s.o.

2020-10-08 14:52 UTC, schmidthappens commented on swagger.yaml
> +          \ wird nicht unterstützt"
Die Beschreibung versteh ich gerade nicht?
Warum muss der Wert `true` sein?

2020-10-09 06:12 UTC, mdehmel commented on swagger.json
> +    "EntscheidungsreifeDTO": {
Ok. Passe ich noch mal an. 
Hab mich bei der Erstellung am Status-Endpunkt orientiert. Bei dem heißt es auch StatusDTO.

2020-10-09 06:13 UTC, mdehmel commented on swagger.yaml
> +          \ wird nicht unterstützt"
Wir unterstützen im Moment nur true.
Die Entscheidungsreife kann nur einmal gesetzt werden. Ein false lehnen wir derzeit ab mit "Du darfst das nicht wieder zurückziehen".

2020-10-13 07:46 UTC, lennartfriedrich approved these changes
I like what i see

2020-10-13 13:56 UTC, mdehmel commented
@roamingthings, @MikeKrueger75 Mag sich jemand für ein Review dieses PR erbarmen? Oder mir alternativ den "besten" Ansprechpartner dafür geben? Die Menschheit wartet darauf, das Entscheidungsreifesignal auch per API senden zu dürfen. :)

2020-10-14 07:15 UTC, merged